PROJECT=lua-unittest
DESCRIPTION=Unit test for multitasking safe variant for printf

DRIVERS=serial
MODULES=scmprintf dispatcher lua

LIBS_PREFIX=
LIBS_SUFFIX= 

include ${SCM_RTOS_DIR}/build/scmRTOS.mk
