PROJECT=shell-unittest
DESCRIPTION=Unit test for multitasking safe variant for printf

DRIVERS=serial ssp
MODULES=newlib shell fatfs mmcfs

LIBS_PREFIX=
LIBS_SUFFIX= 

include ${SCM_RTOS_DIR}/build/scmRTOS.mk
