PROJECT=scmprintf_unittest
DESCRIPTION=Unit test for multitasking safe variant for printf

DRIVERS=serial
MODULES=scmprintf newlib

LIBS_PREFIX=
LIBS_SUFFIX= 


include ${SCM_RTOS_DIR}/build/scmRTOS.mk

FLAGS += -DNEWLIB_VERBOSE 
